highlighter: rouge
markdown: kramdown
kramdown:
  entity_output: symbol
permalink: none
destination: site
exclude: ['README.md', 'content', 'LICENSE', 'merge_pr.py', 'free_disk_space_container', 'Gemfile', 'Gemfile.lock']
keep_files: ['docs', 'static']
url: https://spark.apache.org
